#!/bin/bash
#     ////     //  ////     //
#    // //    //  // //    //
#   //  //   //  //  //   //
#  //   //  //  //   //  //
# //    // //  //    // //
#//     ////  //     ////
#
# 20200407 - BookStack Backup
#
echo "----------------------------------------------"
echo "--[ Backing up BookStack MariaSQL database ]--"
echo "----------------------------------------------"
mysqldump -u nn nnserver > /home/nn/bookstack_backup/BookStack.sql
echo "---------------------------------------------"
echo "--[ Create an archive of files for backup ]--"
echo "---------------------------------------------"
tar -czvf /home/nn/bookstack_backup/bookstack-files-backup.tar.gz /var/www/html/BookStack/.env /var/www/html/BookStack/public/uploads /var/www/html/BookStack/storage/uploads
echo "--------------------------------------------------------"
echo "--[ Create an archive of BookStack folder for backup ]--"
echo "--------------------------------------------------------"
tar -czvf /home/nn/bookstack_backup/bookstack-complete-backup.tar.gz /var/www/html/BookStack
echo "------------------------------------------------------------------------"
echo "Backing up bookstack_backup to vault"
echo "------------------------------------------------------------------------"
#Mounts vault, copies bookstack_backup with date stamp, unmounts
sudo mount -t cifs //192.168.1.111/n1 /mnt/tmp -o credentials=/home/nn/Keys/.vaultpassword
tar -czvf /home/nn/bookstack_backup/ /home/nn/bookstack_backup.tar.gz
cp -r /home/nn/bookstack_backup.tar.gz /mnt/tmp/Files/NNServer/WEB.BookStack_192.168.1.112/Backup/bookstack_backup_"$(date +%Y-%m-%d_%H%M%S)"/
rm /home/nn/bookstack_backup.tar.gz
sudo umount -t cifs //192.168.1.111/n1