#!/bin/bash
#     ////     //  ////     //
#    // //    //  // //    //
#   //  //   //  //  //   //
#  //   //  //  //   //  //
# //    // //  //    // //
#//     ////  //     ////
#
# 20200513 - Cron BookStack Backup
#
#Backing up BookStack MariaSQL database
mysqldump -u nn nnserver > /home/nn/bookstack_backup/BookStack.sql
#Create an archive of BookStack folder for backup
tar -czf /home/nn/bookstack_backup/bookstack-complete-backup.tar.gz /var/www/html/BookStack
#Mounts vault, copies bookstack_backup with date stamp, cleans up, unmounts
mount -t cifs //10.0.100.10/NNVault /mnt/tmp -o credentials=/home/nn/.smbnnvault
tar -czvf /home/nn/bookstack_backup.tar.gz /home/nn/bookstack_backup/
cp -r /home/nn/bookstack_backup.tar.gz /mnt/tmp/Backup/NNServer/WEB.BookStack/Backup/bookstack_backup_"$(date +%Y-%m-%d_%H%M%S)".tar.gz
rm /home/nn/bookstack_backup.tar.gz
rm -r /home/nn/bookstack_backup/*
umount -t cifs //10.0.100.10/NNVault